apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"redis","namespace":"default"},"spec":{"containers":[{"command":["redis-server","/redis-master/redis.conf"],"env":[{"name":"MASTER","value":"true"}],"image":"redis:5.0.4","name":"redis","ports":[{"containerPort":6379}],"resources":{"limits":{"cpu":"0.1"}},"volumeMounts":[{"mountPath":"/redis-master-data","name":"data"},{"mountPath":"/redis-master","name":"config"}]}],"volumes":[{"emptyDir":{},"name":"data"},{"configMap":{"items":[{"key":"redis-config","path":"redis.conf"}],"name":"redis-configmap"},"name":"config"}]}}
  creationTimestamp: "2022-02-04T15:10:39Z"
  name: redis
  namespace: default
  resourceVersion: "97842"
  uid: 42f4fe6e-ad7d-4f35-9668-4b6e67028a58
spec:
  containers:
  - command:
    - redis-server
    - /redis-master/redis.conf
    env:
    - name: MASTER
      value: "true"
    image: redis:5.0.4
    imagePullPolicy: IfNotPresent
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rpkgk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-test-default-pool-6d6a7f5d-8d3t
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: data
  - configMap:
      defaultMode: 420
      items:
      - key: redis-config
        path: redis.conf
      name: redis-configmap
    name: config
  - name: kube-api-access-rpkgk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-04T15:10:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-04T15:10:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-04T15:10:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-04T15:10:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://aa1e7312caaca1b4955dbb5efcb4b2dfb46e2eba1738ed599dbeaf5a81f31027
    image: docker.io/library/redis:5.0.4
    imageID: docker.io/library/redis@sha256:2dfa6432744659268d001d16c39f7be52ee73ef7e1001ff80643f0f7bdee117e
    lastState: {}
    name: redis
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-04T15:10:43Z"
  hostIP: 10.156.0.11
  phase: Running
  podIP: 10.64.5.12
  podIPs:
  - ip: 10.64.5.12
  qosClass: Burstable
  startTime: "2022-02-04T15:10:39Z"
